import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/User.module.css'
import { useState } from 'react'
import Link from 'next/link'
import User from '../components/user'

export async function getStaticProps() {
  const data = await fetch('https://api.github.com/users/ronaldaraujo')
  const users = await data.json()
  return {
    props: {users}
  }
}

export default function Home({users}) {
  const [search, setSearch] = useState('');
  const user = users.name
  const userFilter = user.toLocaleLowerCase().includes(search.toLocaleLowerCase())

  return (
    <>
      <Head>
        <title className="">GitHub User</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <div className='p-10'>
        <form>   
          <label htmlFor="default-search" className="mb-2 text-sm font-medium text-gray-900 sr-only dark:text-gray-300">Search</label>
          <div className="relative">
              <div className="flex absolute inset-y-0 left-0 items-center pl-3 pointer-events-none">
                  <svg aria-hidden="true" className="w-5 h-5 text-gray-500 dark:text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path></svg>
              </div>
              <input type="search" id="default-search" value={search} onChange={(ev) => setSearch(ev.target.value)} className="block p-4 pl-10 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Digite o usuário que deseja encontrar..."/>
          </div>
        </form>

        <div className={styles.container}>
          { !!userFilter && search != "" ? (
            <User users={users}/>
          ) : (
            <h1>Usuário não encontrado</h1>
          )}
        </div>
      </div>
    </>
  )
}
